### PR TITLE
[WIP] Implementation of Storybooks

### LINKED ISSUE #7787: [Tracking] Implement Storybook
Storybook (https://github.com/storybooks/storybook) is an amazing visual tool for rendering react components.  We should implement storybook to cut down on visual regressions, which may include:

- RTL
- Light and dark theme 
- Prefs on/off differences

### PR DESCRIPTION
**Pull request by emanueltimlopez**
Fixes #7787

### Summary of Changes

* implements storybooks tool https://storybook.js.org/

### Usage

run storybook npm script

### TODO
[x] install dependencies sb 
[x] dynamically load stories
[x] configure npm scripts
[x] add welcomebox story
[x] global variables (like L10N)
[ ] configure webpack (inside .storybook folder) <- _npm run storybook_ should run without errors here. For now fails mapping names (resources, chrome, etc) and flow.
[ ] decorator for themes
[ ] install addons
[ ] add storys

### CODE REVIEW

**Comment by darkwing** [comment]
Awesome work @emanueltimlopez !  I love that you've started this!  

Could you update the PR summary with ToDo's so we know what the next steps are?

Thank you!

**Comment by emanueltimlopez** [comment]
@darkwing updated!

**Comment by darkwing** [comment]
Hello @emanueltimlopez!  How is progress on this?  I'm super excited for it! 👍 👍 👍

**Comment by emanueltimlopez** [comment]
Hi! i have no progress in webpack configuration for alias :(

**Comment by darkwing** [comment]
Hello @emanueltimlopez !  I'm going to close this until we have time to make more progress.  Thank you for your efforts and please reopen if you're able to get the basic debugger displaying via storybook!

**Pull request closed without merging**
