### PR TITLE
Add title and hover state to sources list

### LINKED ISSUE #8193: Add hover state and title to sources entries
The sources tree can feel surprisingly non-interactive compared to Chrome

1. Chrome shows the full title of the entry via tooltip, which can help for smaller sources panel widths
2. Chrome has a visual hover state

image

image

_(In both I hover the line after the selected entry, one day I figure out why OSX doesn't capture my cursor even with the option checked)_

Fixes:
1. Add title
2. Add hover state, similar to Inspector and Network panel

### PR DESCRIPTION
**Pull request by anthonyx**
Fixes #8193

Changes:
- Added title via tooltip
- Added hover state

Here's a GIF of the changes. I used the same hover color from `ResultList.css` as suggested by @darkwing.

add-title-hover

### CODE REVIEW

**Comment by darkwing** [comment]
This is awesome.  I'm going to wait on merging this until (https://phabricator.services.mozilla.com/D29225) is merged -- it's a massive tree overhaul.

In the mean time @anthonyx , feel free to push this over to Phabricator if you get time.

**Comment by jasonLaster** [comment]
What are the benefits of the title change? Perhaps long sources that are clipped...

**Comment by darkwing** [comment]
This will probably need rebasing after https://github.com/firefox-devtools/debugger/pull/8217 goes in -- I'm working to get that in now.

**Comment by darkwing** [comment]
Could you rebase or move to Phabricator @anthonyx ?  Thank you!

**Comment by darkwing** [comment]
Superceded by https://phabricator.services.mozilla.com/D33019

**Pull request closed without merging**
