### PR TITLE
Issue 8127 fix (primary panel missing bottom border)

### LINKED ISSUE #8127: Primary panel is missing a bottom border
When you open the debugger without any tabs selected, and they primary panel is small enough, it misses the bottom border.

### PR DESCRIPTION
**Pull request by derek-li**
Fixes #8127 

### Summary of Changes

* Adjusted z-index of `SplitBox.css`, `WelcomeBox.css`, and `Footer.css` to always place splitters at the very top resolving inconsistent splitter thickness
* Increased vertical mode splitter thickness by 1px and increased visibility with `hover` to make the splitter color change. I'm not sure which color to use, @fvsch do you have any input on this?
* Set `maxSize="70%"`  (previously set to 70% in horizontal mode and 95% in vertical mode which didn't make sense to me because what can you see with 5% of the window) to the initial `SplitBox` preventing either primary or secondary panes from becoming too small
bbeebfec468ed5f55b92afe66ed05c63
(pane can't grow passed certain size)

### CODE REVIEW

**Comment by darkwing** [comment]
Nice @derek-li !  Could you rebase?  The Travis failure isn't legit.

**Comment by fvsch** [comment]
> Increased vertical mode splitter thickness by 1px and increased visibility with hover to make the splitter color change. I'm not sure which color to use, @fvsch do you have any input on this?

@derek-li The relevant colors are defined as CSS variables, you should be able to use them directly:
https://searchfox.org/mozilla-central/source/devtools/client/themes/variables.css#46-47

**Comment by darkwing** [comment]
@fvsch Care to have another look?

**Comment by darkwing** [comment]
@derek-li I'm seeing this issue when pulling up:

PullUp

For the sake of continuity, I think we'd want the header area to display above a footer.

**Comment by darkwing** [comment]
Also, I think we should move the splitter width/hover stuff to a different PR -- let's keep this one ultra focused on just the issue reported.

**Comment by derek-li** [comment]
@darkwing Added the fix for the issue you found.

Just wondering, would you want me to move the `minSize` `maxSize` changes also since they don't directly pertain to the issue?

**Comment by darkwing** [comment]
Superceded by: https://phabricator.services.mozilla.com/D33025

**Pull request closed without merging**
