### PR TITLE
Update links and help for first contributions

### LINKED ISSUE #8030: [Docs] Update links and help for first contributions
For the first contributors, the information can be misunderstood because some links are pointing to old content or to none.

- The CONTRIBUTING.md does not mention the tag "good first issue". Will be good to include in the description for first contributions that bot tags are a good way to find issues.
- The link in the contributing.md to "help wanted" label is not working after the rename of the tags to include emoticons, the link should be to **label:":wave: help wanted"**

### PR DESCRIPTION
**Pull request by soniasingla**
Fixes #8030 

###Summary of Changes

Updated links and help for first contributions :smile:

### CODE REVIEW

**Comment by charanjit-singh** [comment]
@soniasingla  Can you change the Title of this pull request. Change it to more meaningful like:
"Update links and help for first contributions" . "Update" alone is not enough.

**Comment by darkwing** [comment]
Hello @soniasingla -- could you remove the `996a7ec` file?  Thank you!

**Comment by darkwing** [comment]
It appears @soniasingla no longer has a fork of this repo.  I'm closing this, but would be happy if someone picked it up!

**Comment by soniasingla** [comment]
@darkwing actually I changed my machine. I am sorry for the delay and will raise a new PR.

**Pull request closed without merging**
