### PR TITLE
8064-footer

### LINKED ISSUE #8064: Footer content can be centered instead of aligned-right
Footer layout:

```jsx
<div className="source-footer">
  {this.renderCommands()}
  {this.renderSourceSummary()}
  {this.renderCursorPosition()}
  {this.renderToggleButton()}
</div>
```

The commands are rendered in their own wrapping <div>, but other content are single items which all have `margin-inline-start: auto`. When we end up rendering more than one (summary + position, position + toggle button...), those elements end up spaced evenly and look centered in the footer.

We should probably have:

```jsx
<div className="source-footer">
  <div className="source-footer-start">
    {this.renderCommands()}
  </div>
  <div className="source-footer-end">
    {this.renderSourceSummary()}
    {this.renderCursorPosition()}
    {this.renderToggleButton()}
  </div>
</div>
```

### PR DESCRIPTION
**Pull request by errietta**
Fixes #8064 

Here's the Pull Request Doc
https://firefox-dev.tools/debugger/docs/pull-requests.html

### Summary of Changes

* Split controls to the left and rest of icons on the right

### Test plan

* Check with different permutations of what can appear/not appear
For example the 'pretty print' button will show on minified source, the "from" information will show if there's a source map

### Screenshots/Videos (OPTIONAL)
Screenshot 2019-03-24 at 22 45 00

### CODE REVIEW

**Comment by darkwing** [comment]
This is a great start @errietta ! 

The only problem I noticed was that the button hover no longer takes up the full height:  

buttonhover

**Comment by errietta** [comment]
@darkwing I don't understand the difference, maybe I can't see it...

Master:
image
this branch:
Screenshot 2019-03-25 at 22 47 10

**Comment by errietta** [comment]
Oh. I just saw it, the hover its too short, will look

**Comment by darkwing** [comment]
It's easier to see in light mode; hover over the eye in light mode, on master, and the hover color takes up the entire vertical space.  In this patch, it shows spacing above and below the buttonn.

**Comment by errietta** [comment]
@darkwing yeah figured, have a fix pushed

**Comment by errietta** [comment]
@darkwing any idea what's wrong with the travis build?

**Comment by darkwing** [comment]
I'm looking into it :/

**Comment by darkwing** [comment]
Rebasing your PR on master should fix the Travis issue :)

**Comment by errietta** [comment]
@darkwing nooope :/

**Comment by errietta** [comment]
@darkwing it passed w00t

**Comment by darkwing** [comment]
Seeing one small issue:  
StackedButtons

**Comment by errietta** [comment]
GAH. Must have borked from the rbase :/ will look

**Comment by errietta** [comment]
should be fixed. altho i made the `.commands` class flex, which i'm not sure is the cleanest solution.. my css is like a chicken with crayons 🐔 ✏️

**Comment by darkwing** [comment]
Functionally this is great -- good work!  

In your CSS, I don't think you need the `>` in your selectors though -- please try without those.  Once we've confirmed, we can merge.  Thank you!

**Comment by errietta** [comment]
I was just doing the same as was already done, I can change it :)

**Comment by darkwing** [comment]
Ahh, sorry @errietta , I didn't notice that 👍

**Pull request merged**
