### PR TITLE
Revert "ligned breakpoints and XHR breakpoints panes (#8094)"

### PR DESCRIPTION
**Pull request by darkwing**
This reverts commit 6b4110eaf3638c3635b765b1b4781d8ca7b6cf7b.

I missed a few CSS issues with this PR that I've spotted later:

1.  There's too much space above and below the the expression and XHR inputs
2.  The breakpoint line-height seems small

FewUIIssues

### CODE REVIEW

**Comment by darkwing** [comment]
@jaril Alternatively a new PR with a few fixes would be excellent too!

cc @fvsch

**Comment by fvsch** [comment]
@darkwing As far as I can see, everything is going according to plan. :)

The issues you're seeing are IMO due to two things:

1. Probably the force of habit. We changed some things, giving padding to accordion content and making content rows tighter (20px height, instead of the previous semi-random heights in the 26-30px range). Breakpoint rows were the most airy of all secondary pane content, contrasting a lot with the very squished Scopes, so now the 20px-tall breakpoint rows may seem too small.

2. We haven't landed all the work on secondary panes vertical rhythm, so there are some strong visual differences between the inputs in Watch Expressions (tall, to be fixed) and XHR Breakpoints (narrower, fixed).

My take is that we should land and/or work on the remaining bits that address spacing in Secondary Panes (following @jaril's comprehensive mockups), review the complete result when we're done, and make adjustments then.

Pieces to land and/or work on:

- #8066 (Watch expressions and Scopes)
- #8141 (XHR breakpoint method select)
- #8149 (Threads pane)

> There's too much space above and below the the expression and XHR inputs

The XHR input is actually closer to the spec. The 4px of empty space before and after the input is intented. It's not a great solution, but it's the more rational way to manage situations where the UI has a series of existing rows plus an input row; we would like the input row to use the same height as the saved rows (20px), to make things more cohesive and to avoid vertical jumps.

**Comment by darkwing** [comment]
Thank you for the update @fvsch!  I appreciate the detail!

We're very early in the next FF cycle so I'm fine with additions or fixes.  Not to disparage your or @jaril's work, but the space above and below the Expression and XHR BP feels like an eye sore; as a user, I kind of see it as an obvious "mistake"; it makes the input area seem very big, especially when all of the other "rows" (breakpoints, scopes, etc.) have become so "thin".

I'm good with the thinner rows but I'd really like us to figure out how to make the input areas not seem so large.

**Comment by fvsch** [comment]
The watch expression one is definitely too large, but merging Jaril's PR would help. :)

If we keep the inputs at 20px and the current padding (in XHR Breakpoint), that's a 28px height total, same height as the same pane with one XHR Breakpoint set up. So I'm not worried about it looking too big.

I'm a bit worried about the padding looking like a sore thumb when we just have one input, though. But it will be clearer to see if we need changes there once the PRs land and the dust settles.

**Pull request closed without merging**
