### PR TITLE
Fix #7956 - Show falsy values in preview

### LINKED ISSUE #7956: [Preview] should show "false" in the tooltip
we currently do not show a tooltip wheh you  hover on a token that evaluates to false. I think we should show one because it is confusing when you do not see it.

### PR DESCRIPTION
**Pull request by darkwing**
Fixes #7956

Good manual testing:  
 - Basic: http://breezy-join.glitch.me/
 - Previously found brick case:  https://github.com/firefox-devtools/debugger/pull/8056#issue-257591385

I also updated the test that had these values commented out.

### CODE REVIEW

**Comment by darkwing** [comment]
cc @ravefalcon92

**Comment by ravefalcon92** [comment]
Just tested the solution on a series of different values and it looks like everything is displaying properly in the preview. Thanks for tracking down that bricking behavior @darkwing!

**Comment by jasonLaster** [comment]
@WenInCode are you noticing that sometimes preview doesn't work the first time?

**Comment by WenInCode** [comment]
@jasonLaster I haven't noticed that. I think that looks like the case in the gif I posted, but it was because the debugger window wasn't actually in focus, my screen recorder was.

**Comment by WenInCode** [comment]
Just double checked on the examples a few times to see if i could get the preview to not work on first try. I was unable to get that issue. The preview worked each time 👍

**Pull request merged**
