### PR TITLE
Update pull-requests.md

### PR DESCRIPTION
**Pull request by kevinmorehouse**
Expanded key sections to make the document more accessible. Also made spelling, grammar, and style fixes for clarity. 

Fixes # N/A
### Summary of Changes

* Spelling and grammar fixes
* Formatting fixes
* Capitalization fixes
* Replaced acronyms with full phrases in key locations (for clarity)
* Bolded key phrases for clarity
* Added mention of Travis in CI section
* Expanded section on fixing false positives in spellchecker
* Added links to key GitHub docs
* Added introduction

### CODE REVIEW

**Comment by kevinmorehouse** [comment]
One thing I want to bring attention to here: 

On line 223, in the _Continuous Integration_ section, I added a reference to _Travis CI_, as well as a link to `.travis.yml`. The goal was to match how _Circle CI_ was mentioned in the same line. 

My question is, does `.travis.yml` qualify as a "test run", like `config.yml` does? Or is everything handled *just* by `config.yml`, making the mention of Travis and `.travis.yml` unnecessary?

**Comment by darkwing** [comment]
Travis runs the mochitests, so it's worth a mention :)

**Comment by darkwing** [comment]
You'll also need to remove the jest test update -- I don't think you wanted to submit that.

**Comment by kevinmorehouse** [comment]
@darkwing Okay, we should be good to go now. I just forgot to rebase, which seems to have been the cause of the jest tests issue. 

(In attempting to solve the issue, I seem to have accidentally requested a PR review from @flodolo. That was an error on my part, but I do not seem to have the means to remove the review request on my end. Sorry for any inconvenience!)

**Comment by flodolo** [comment]
> (In attempting to solve the issue, I seem to have accidentally requested a PR review from @flodolo. That was an error on my part, but I do not seem to have the means to remove the review request on my end. Sorry for any inconvenience!)

No worry, it happens to everyone to fight with merges and rebases. I can ignore the thread.

**Comment by darkwing** [comment]
Awesome!  Thank you @kevinmorehouse !

**Pull request merged**
