### PR TITLE
Update name of repository

### PR DESCRIPTION
**Pull request by kevinmorehouse**
Updated doc to reflect new name of repository (_debugger_) and removed references to old repository name (_debugger.html_), as decided in PR #8009 .

Fixes N/A

### Summary of Changes

* Replaced any instances of _debugger.html_ with _debugger_ (or removed them altogether)
* Fixed capitalization of "debugger" on line 60.

### CODE REVIEW

**Comment by kevinmorehouse** [comment]
Am I correct in assuming that the directory name on line 32 should be changed from _debugger.html_ to _debugger_, along with the rest of the changes?

**Comment by kevinmorehouse** [comment]
The _community call_ link (on lines 83 and 114) still points to https://appear.in/debugger.html.

Is the team going to still meet at that url, or are you going to use a new one now?

**Comment by jasonLaster** [comment]
I think we should change debugger.html, but that also means updating appear.in too!

**Comment by jasonLaster** [comment]
Okay, nevermind i think that is taken, lets use `https://appear.in/firefox-debugger`

**Pull request merged**
