### PR TITLE
Project-search improvement ( Add redux to ProjectSearch ) | Also Fixes #7967

### LINKED ISSUE #7967: Search for text with braces in pattern.
When i try to search in source (ctrl+shift+f) wth braces in pattern i find nothing 
ex: `parameters = Object.assign({node: null}, parameters);`
Then i must escape all braces, which is very annoying, to find what i need.
ex: `parameters = Object.assign\({node: null}, parameters\);`

I propose to search with text pattern by default (like in old versions). Regex search pattern should be an option.

### PR DESCRIPTION
**Pull request by charanjit-singh**
Fixes #7967

Project Search can be opened using `Ctrl + Shift + F`.

### Summary of Changes

* Added Redux to ProjectSearch. Now instead of passing Query string to search function, reducers, actions and state will take care of that.
* Added Modifiers on project search.  
  - RegexMatch
  - CaseSensitive
  - WholeWord
* Addded UI to control Modifiers.

### Test Plan

Testing on searching will be done by entering input query, modifiers and match them with expected results.

Example test plan:

- [x] Ctrl + Shift + F to open the Project Search
- [x] Focusing on Input Field.
- [x] Clicking on Modifier buttons to toggle their values.
- [x] Pressing `[Enter]` to start search.
- [x] Match the results with expected results.
- [x] Clicking "x" closes the search.

### CODE REVIEW

**Comment by charanjit-singh** [comment]
@darkwing I need someone to update the snapshot files.

**Comment by charanjit-singh** [comment]
@darkwing do you need summary of what I did in what order?

**Comment by AnshulMalik** [comment]
That would help @charanjit-singh. And I see some fuse files as well, can we get rid of them?

**Comment by darkwing** [comment]
Thank you for this submission @charanjit-singh !  

This PR goes a bit beyond the original bug you cited.  Could you open a new PR with just the fix for said issue?

As for this larger PR and feature, there's some work that need to come beforehand, like unifying the UI.  Again, this is amazing work, but let's take a more focused, prioritized approach.

**Comment by charanjit-singh** [comment]
@darkwing I changed whole structure because I cannot just edit the SearchInput Component for that as it is conflicting with the SearchInput of In-File Search. That's Why I arranged Everything in proper manner.

**Pull request closed without merging**
