### PR TITLE
added no sources message in Sources Pane

### LINKED ISSUE #7966: "No Sources" message no longer displays
We used to have a message when no sources were on a give page -- now we have none:

devtoolsnosources

### PR DESCRIPTION
**Pull request by harshlele**
Fixes #7966

### Summary of Changes

* Added a "No Sources" message in the sources pane when there are no sources on a page

### CODE REVIEW

**Comment by darkwing** [comment]
@jasonLaster Could you check this out since you'll be doing worker tree stuff?  Thank you!

**Comment by bomsy** [comment]
Actually it might be nice to add a test for this scenario as well, so it does not regress again.

**Comment by darkwing** [comment]
Awesome work @harshlele !  I think @bomsy is right here; we should add a Jest test to ensure we don't regress.  Have a look at our jest tests and let me know if you have questions!

**Comment by harshlele** [comment]
hey sorry for not responding, was on vacation, i'll check the tests now.

**Comment by darkwing** [comment]
Thank you @harshlele!  I'll check in on Monday!

**Comment by harshlele** [comment]
@darkwing hey i've added the test.

**Pull request merged**
